export {};

const DEFAULT_BASE_URL = 'https://inference.do-ai.run';
const MAX_CONCURRENT_STREAMS = 2;
const AUTO_CONTINUE_LIMIT = 3;
const AUTO_CONTINUE_REDUCTION = 0.8;
const MIN_AUTO_MAX_TOKENS = 64;
const METRICS_WINDOW_MS = 5 * 60 * 1000;
const SUPPORTS_STREAM = typeof ReadableStream !== 'undefined' && typeof Response !== 'undefined';

/**
 * @typedef {'system'|'user'|'assistant'} ChatRole
 * @typedef {{role: ChatRole, content: string}} OutgoingMessage
 * @typedef {{prompt_tokens?: number, completion_tokens?: number, total_tokens?: number}} TokenUsage
 * @typedef {{
 *   id: string;
 *   role: ChatRole;
 *   content: string;
 *   createdAt: number;
 *   finishReason?: string;
 *   usage?: TokenUsage;
 *   requestId?: string | null;
 *   streaming?: boolean;
 *   error?: string | null;
 *   queued?: boolean;
 *   autoGenerated?: boolean;
 *   statusNote?: string;
 * }} StoredMessage
 * @typedef {{
 *   baseUrl: string;
 *   model: string;
 *   temperature: number;
 *   top_p: number;
 *   max_tokens: number;
 *   rememberKey: boolean;
 * }} AppSettings
 * @typedef {{ messages: StoredMessage[]; settings: AppSettings; models: string[]; modelStatus: string; }} StoreSnapshot
 * @typedef {{ status: number; ttft?: number; finishReason?: string; note?: string }} RequestSummary
 * @typedef {{
 *   totals: { prompt: number; completion: number; total: number };
 *   rateLimitCount: number;
 *   retryCount: number;
 *   ttft: number[];
 *   ttftP95: number | null;
 *   failures: Record<string, number>;
 *   requestSummaries: RequestSummary[];
 * }} MetricsSnapshot
 * @typedef {{ id: string; userMessageId: string; assistantMessageId: string; autoGenerated: boolean; autoDepth: number; maxTokens: number; controller: AbortController }} ChatQueueItem
 * @typedef {{ content: string; finishReason?: string; usage?: TokenUsage; requestId: string | null; ttft?: number; notice?: string }} ChatResult
 * @typedef {{ autoGenerated?: boolean; autoDepth?: number; maxTokens?: number }} SendOptions
 */

class ApiError extends Error {
  /** @param {string} message @param {{ status: number, payload?: unknown, headers?: Headers }} options */
  constructor(message, options) {
    super(message);
    this.name = 'ApiError';
    this.status = options.status;
    this.payload = options.payload;
    this.headers = options.headers;
  }
}

class Backoff {
  constructor(initialMs, factor, maxMs, maxAttempts) {
    this.initial = initialMs;
    this.factor = factor;
    this.max = maxMs;
    this.maxAttempts = maxAttempts;
    this.attempt = 0;
  }

  next() {
    this.attempt += 1;
    const value = this.initial * Math.pow(this.factor, this.attempt - 1);
    return Math.min(value, this.max);
  }

  reset() {
    this.attempt = 0;
  }
}

class Metrics {
  constructor() {
    this.totals = { prompt: 0, completion: 0, total: 0 };
    this.ttft = [];
    this.rateLimitEvents = [];
    this.retryEvents = [];
    this.failureMap = new Map();
    this.listeners = new Set();
    this.requestSummaries = [];
  }

  /** @param {TokenUsage | null | undefined} usage */
  recordUsage(usage) {
    if (!usage) {
      return;
    }
    const { prompt_tokens, completion_tokens, total_tokens } = usage;
    if (typeof prompt_tokens === 'number') {
      this.totals.prompt += prompt_tokens;
    }
    if (typeof completion_tokens === 'number') {
      this.totals.completion += completion_tokens;
    }
    if (typeof total_tokens === 'number') {
      this.totals.total += total_tokens;
    }
    this.emit();
  }

  /** @param {number} ms */
  recordTTFT(ms) {
    if (!Number.isFinite(ms)) {
      return;
    }
    const entry = { ms, timestamp: Date.now() };
    this.ttft.push(entry);
    if (this.ttft.length > 20) {
      this.ttft.splice(0, this.ttft.length - 20);
    }
    this.emit();
  }

  recordRateLimit() {
    this.rateLimitEvents.push(Date.now());
    this.emit();
  }

  recordRetry() {
    this.retryEvents.push(Date.now());
    this.emit();
  }

  /** @param {string} code */
  recordFailure(code) {
    const prev = this.failureMap.get(code) ?? 0;
    this.failureMap.set(code, prev + 1);
    this.emit();
  }

  /** @param {RequestSummary} summary */
  recordRequestSummary(summary) {
    this.requestSummaries.push({ timestamp: Date.now(), ...summary });
    if (this.requestSummaries.length > 50) {
      this.requestSummaries.splice(0, this.requestSummaries.length - 50);
    }
    this.emit();
  }

  /** @param {(snapshot: MetricsSnapshot) => void} listener */
  subscribe(listener) {
    this.listeners.add(listener);
    listener(this.snapshot());
    return () => {
      this.listeners.delete(listener);
    };
  }

  /** @returns {MetricsSnapshot} */
  snapshot() {
    this.prune();
    const ttftValues = this.ttft.map((item) => item.ms);
    const p95 = this.computeP95(ttftValues);
    const failures = {};
    for (const [key, value] of this.failureMap.entries()) {
      failures[key] = value;
    }
    return {
      totals: { ...this.totals },
      rateLimitCount: this.rateLimitEvents.length,
      retryCount: this.retryEvents.length,
      ttft: ttftValues.slice().reverse(),
      ttftP95: p95,
      failures,
      requestSummaries: this.requestSummaries.slice(-20),
    };
  }

  /** @returns {string} */
  exportNDJSON() {
    const snapshot = this.snapshot();
    const lines = [];
    lines.push(JSON.stringify({ type: 'totals', timestamp: Date.now(), data: snapshot.totals }));
    lines.push(JSON.stringify({ type: 'window', timestamp: Date.now(), rateLimitCount: snapshot.rateLimitCount, retryCount: snapshot.retryCount, ttftP95: snapshot.ttftP95 }));
    snapshot.requestSummaries.forEach((summary) => {
      lines.push(JSON.stringify({ type: 'request', ...summary }));
    });
    Object.entries(snapshot.failures).forEach(([code, count]) => {
      lines.push(JSON.stringify({ type: 'failure', code, count }));
    });
    return lines.join('\n');
  }

  prune() {
    const threshold = Date.now() - METRICS_WINDOW_MS;
    this.rateLimitEvents = this.rateLimitEvents.filter((ts) => ts >= threshold);
    this.retryEvents = this.retryEvents.filter((ts) => ts >= threshold);
    this.ttft = this.ttft.filter((item) => item.timestamp >= threshold || this.ttft.length <= 20);
  }

  /** @param {number[]} values @returns {number|null} */
  computeP95(values) {
    if (values.length === 0) {
      return null;
    }
    const sorted = values.slice().sort((a, b) => a - b);
    const idx = Math.min(sorted.length - 1, Math.floor(0.95 * (sorted.length - 1)));
    return Math.round(sorted[idx]);
  }

  emit() {
    const snapshot = this.snapshot();
    for (const listener of this.listeners) {
      listener(snapshot);
    }
  }
}

class Store {
  constructor() {
    this.settings = {
      baseUrl: DEFAULT_BASE_URL,
      model: 'llama3.3-70b-instruct',
      temperature: 0.2,
      top_p: 0.95,
      max_tokens: 512,
      rememberKey: false,
    };
    this.messages = [];
    this.listeners = new Set();
    this.models = ['llama3.3-70b-instruct'];
    this.apiKey = '';
    this.modelStatus = '待获取模型列表';
    this.sessionKey = 'gradient-serverless-chat-key';
    this.loadSessionKey();
  }

  loadSessionKey() {
    try {
      const value = sessionStorage.getItem(this.sessionKey);
      if (value) {
        this.apiKey = value;
        this.settings.rememberKey = true;
      }
    } catch (error) {
      console.warn('无法读取 sessionStorage', error);
    }
  }

  /** @param {(snapshot: StoreSnapshot) => void} listener */
  subscribe(listener) {
    this.listeners.add(listener);
    listener(this.snapshot());
    return () => {
      this.listeners.delete(listener);
    };
  }

  /** @returns {StoreSnapshot} */
  snapshot() {
    return {
      messages: this.messages.slice(),
      settings: { ...this.settings },
      models: this.models.slice(),
      modelStatus: this.modelStatus,
    };
  }

  /** @returns {AppSettings} */
  getSettings() {
    return { ...this.settings };
  }

  /** @param {Partial<AppSettings>} partial */
  updateSettings(partial) {
    const previousRemember = this.settings.rememberKey;
    this.settings = { ...this.settings, ...partial };
    if (previousRemember !== this.settings.rememberKey) {
      if (this.settings.rememberKey) {
        this.persistKey();
      } else {
        this.removeSessionKey();
      }
    }
    this.emit();
  }

  /** @param {Omit<StoredMessage, 'createdAt'> & { createdAt?: number }} message */
  addMessage(message) {
    const item = {
      ...message,
      createdAt: message.createdAt ?? Date.now(),
    };
    this.messages.push(item);
    this.emit();
    return item;
  }

  /** @param {string} id @param {Partial<StoredMessage>} patch */
  updateMessage(id, patch) {
    const index = this.messages.findIndex((msg) => msg.id === id);
    if (index >= 0) {
      this.messages[index] = { ...this.messages[index], ...patch };
      this.emit();
    }
  }

  clearMessages() {
    this.messages = [];
    this.emit();
  }

  /** @returns {StoredMessage[]} */
  getMessages() {
    return this.messages.slice();
  }

  /** @returns {OutgoingMessage[]} */
  getConversationMessages() {
    return this.messages.map((msg) => ({ role: msg.role, content: msg.content }));
  }

  /** @param {string[]} models */
  setModels(models) {
    if (models.length === 0) {
      return;
    }
    const merged = Array.from(new Set(models.concat('llama3.3-70b-instruct')));
    this.models = merged;
    this.emit();
  }

  /** @param {string} status */
  setModelStatus(status) {
    this.modelStatus = status;
    this.emit();
  }

  /** @returns {string} */
  getApiKey() {
    return this.apiKey;
  }

  /** @param {string} value */
  setApiKey(value) {
    this.apiKey = value;
    if (this.settings.rememberKey) {
      this.persistKey();
    }
    this.emit();
  }

  clearApiKey() {
    this.apiKey = '';
    this.removeSessionKey();
    this.emit();
  }

  persistKey() {
    if (!this.settings.rememberKey) {
      return;
    }
    try {
      if (this.apiKey) {
        sessionStorage.setItem(this.sessionKey, this.apiKey);
      }
    } catch (error) {
      console.warn('无法写入 sessionStorage', error);
    }
  }

  removeSessionKey() {
    try {
      sessionStorage.removeItem(this.sessionKey);
    } catch (error) {
      console.warn('无法删除 sessionStorage', error);
    }
  }

  emit() {
    const snapshot = this.snapshot();
    for (const listener of this.listeners) {
      listener(snapshot);
    }
  }
}

class SseParser {
  /** @param {ReadableStream<Uint8Array>} stream */
  static async *streamLines(stream) {
    const reader = stream.getReader();
    const decoder = new TextDecoder('utf-8');
    let buffer = '';
    let eventBuffer = '';
    while (true) {
      const result = await reader.read();
      if (result.done) {
        if (eventBuffer.trim().length > 0) {
          yield eventBuffer.trim();
        }
        break;
      }
      buffer += decoder.decode(result.value, { stream: true });
      let idx = 0;
      while (idx < buffer.length) {
        const newlineIndex = buffer.indexOf('\n', idx);
        if (newlineIndex === -1) {
          break;
        }
        const line = buffer.slice(idx, newlineIndex).replace(/\r$/, '');
        idx = newlineIndex + 1;
        if (line === '') {
          if (eventBuffer.length > 0) {
            yield eventBuffer.trim();
            eventBuffer = '';
          }
          continue;
        }
        if (line.startsWith('data:')) {
          eventBuffer += `${line.slice(5).trim()}\n`;
        }
      }
      buffer = buffer.slice(idx);
    }
  }
}

class ApiClient {
  /** @param {Store} store @param {Metrics} metrics */
  constructor(store, metrics) {
    this.store = store;
    this.metrics = metrics;
  }

  /** @param {string} path */
  resolve(path) {
    const base = this.store.getSettings().baseUrl.replace(/\/$/, '');
    return `${base}${path}`;
  }

  /** @param {AbortSignal|undefined} signal */
  async fetchModels(signal) {
    const url = this.resolve('/v1/models');
    const headers = this.buildHeaders();
    const response = await fetch(url, { method: 'GET', headers, signal });
    if (!response.ok) {
      let message = `获取模型失败 (${response.status})`;
      try {
        const data = await response.json();
        if (data && typeof data === 'object' && 'error' in data) {
          const error = data.error;
          if (error && typeof error === 'object' && 'message' in error && typeof error.message === 'string') {
            message = error.message;
          }
        }
      } catch (error) {
        console.warn('解析模型列表失败', error);
      }
      throw new ApiError(message, { status: response.status, headers: response.headers });
    }
    const payload = await response.json();
    if (!payload || typeof payload !== 'object' || !Array.isArray(payload.data)) {
      throw new ApiError('模型列表格式不正确', { status: response.status });
    }
    const ids = payload.data
      .map((item) => item && typeof item === 'object' ? item.id : null)
      .filter((id) => typeof id === 'string')
      .map((id) => id);
    return ids.sort();
  }

  async testConnection(signal) {
    await this.fetchModels(signal);
    return true;
  }

  /**
   * @param {Record<string, unknown>} payload
   * @param {{ signal: AbortSignal; onDelta?: (delta: string) => void; onRequestId?: (id: string | null) => void }} options
   * @returns {Promise<ChatResult>}
   */
  async streamChat(payload, options) {
    const requestPayload = SUPPORTS_STREAM ? { ...payload, stream: true } : { ...payload, stream: false };
    const response = await fetch(this.resolve('/v1/chat/completions'), {
      method: 'POST',
      headers: this.buildHeaders(),
      body: JSON.stringify(requestPayload),
      signal: options.signal,
    });

    if (!response.ok) {
      let message = `请求失败 (${response.status})`;
      let payloadDetails = undefined;
      try {
        const data = await response.json();
        payloadDetails = data;
        if (data && typeof data === 'object' && 'error' in data) {
          const error = data.error;
          if (error && typeof error === 'object' && 'message' in error && typeof error.message === 'string') {
            message = error.message;
          }
        }
      } catch (parseError) {
        const text = await response.text().catch(() => '');
        if (text) {
          message = text;
        }
      }
      throw new ApiError(message, { status: response.status, payload: payloadDetails, headers: response.headers });
    }

    const requestId = response.headers.get('x-request-id')
      ?? response.headers.get('x-openai-request-id')
      ?? response.headers.get('x-gradient-request-id');
    if (options.onRequestId) {
      options.onRequestId(requestId);
    }

    const started = performance.now();
    let ttftRecorded = false;
    let aggregated = '';
    let finishReason;
    let usage;

    if (SUPPORTS_STREAM && response.body && typeof response.body.getReader === 'function') {
      try {
        for await (const chunk of SseParser.streamLines(response.body)) {
          if (chunk === '[DONE]') {
            break;
          }
          if (!chunk) {
            continue;
          }
          let parsed;
          try {
            parsed = JSON.parse(chunk);
          } catch (error) {
            console.warn('SSE JSON 解析失败', error, chunk);
            continue;
          }
          if (!parsed || typeof parsed !== 'object') {
            continue;
          }
          const choices = parsed.choices;
          if (Array.isArray(choices) && choices.length > 0) {
            const choice = choices[0];
            if (choice && typeof choice === 'object') {
              const delta = choice.delta;
              if (delta && typeof delta === 'object' && typeof delta.content === 'string' && delta.content.length > 0) {
                aggregated += delta.content;
                if (!ttftRecorded) {
                  const ttft = performance.now() - started;
                  this.metrics.recordTTFT(ttft);
                  ttftRecorded = true;
                }
                if (options.onDelta) {
                  options.onDelta(delta.content);
                }
              }
              if (typeof choice.finish_reason === 'string') {
                finishReason = choice.finish_reason;
              }
            }
          }
          if (parsed.usage) {
            usage = parsed.usage;
          }
        }
      } catch (error) {
        if (error && typeof error === 'object' && 'name' in error && error.name === 'AbortError') {
          throw error;
        }
        console.error('读取流失败', error);
        throw new ApiError('流式解析失败', { status: 0, payload: { cause: 'stream' } });
      }
    } else {
      const json = await response.json();
      const choices = json.choices;
      if (Array.isArray(choices) && choices.length > 0) {
        const choice = choices[0];
        const message = choice && typeof choice === 'object' ? choice.message : undefined;
        const text = message && typeof message === 'object' && typeof message.content === 'string' ? message.content : '';
        aggregated += text;
        finishReason = choice && typeof choice === 'object' ? choice.finish_reason : undefined;
        usage = json.usage;
        if (options.onDelta && text) {
          options.onDelta(text);
        }
      }
      if (!ttftRecorded) {
        this.metrics.recordTTFT(performance.now() - started);
        ttftRecorded = true;
      }
    }

    if (!ttftRecorded) {
      this.metrics.recordTTFT(performance.now() - started);
    }
    this.metrics.recordUsage(usage);

    return {
      content: aggregated,
      finishReason,
      usage,
      requestId,
      ttft: performance.now() - started,
      notice: usage ? undefined : 'usage 未返回',
    };
  }

  buildHeaders() {
    const headers = new Headers();
    headers.set('Content-Type', 'application/json');
    const key = this.store.getApiKey();
    if (key) {
      headers.set('Authorization', `Bearer ${key}`);
    }
    return headers;
  }
}

/** @typedef {{ dismiss: () => void }} ToastHandle */

class UI extends EventTarget {
  /** @param {Store} store @param {Metrics} metrics */
  constructor(store, metrics) {
    super();
    this.store = store;
    this.metrics = metrics;
    this.messageList = document.getElementById('messageList');
    this.textarea = document.getElementById('chatInput');
    this.sendButton = document.getElementById('sendButton');
    this.queueStatus = document.getElementById('queueStatus');
    this.settingsDialog = document.getElementById('settingsDialog');
    this.modalBackdrop = this.settingsDialog ? this.settingsDialog.querySelector('.modal-backdrop') : null;
    this.settingsForm = document.getElementById('settingsForm');
    this.toastContainer = document.getElementById('toastContainer');
    this.monitorPanel = document.getElementById('monitorPanel');
    this.toggleSidebarButton = document.getElementById('toggleSidebar');
    this.metricPrompt = document.getElementById('metricPrompt');
    this.metricCompletion = document.getElementById('metricCompletion');
    this.metricTotal = document.getElementById('metricTotal');
    this.metricRateLimits = document.getElementById('metricRateLimits');
    this.metricRetries = document.getElementById('metricRetries');
    this.metricTtftP95 = document.getElementById('metricTtftP95');
    this.metricTtftList = document.getElementById('metricTtftList');
    this.metricFailures = document.getElementById('metricFailures');
    this.modelSelect = document.getElementById('modelSelect');
    this.manualModelInput = document.getElementById('manualModelInput');
    this.apiKeyInput = document.getElementById('apiKeyInput');
    this.rememberKey = document.getElementById('rememberKey');
    this.baseUrlInput = document.getElementById('baseUrlInput');
    this.temperatureInput = document.getElementById('temperatureInput');
    this.topPInput = document.getElementById('topPInput');
    this.maxTokensInput = document.getElementById('maxTokensInput');
    this.modelStatus = document.getElementById('modelStatus');
    this.testConnectionButton = document.getElementById('testConnection');
    this.refreshModelsButton = document.getElementById('refreshModels');
    this.clearKeyButton = document.getElementById('clearKeyButton');
    this.exportButton = document.getElementById('exportButton');
    this.settingsButton = document.getElementById('settingsButton');
    this.clearButton = document.getElementById('clearButton');
    this.exportMetricsButton = document.getElementById('exportMetrics');
    this.messageMap = new Map();
    this.ensureElements();
    this.attachEvents();
  }

  ensureElements() {
    const elements = [
      this.messageList,
      this.textarea,
      this.sendButton,
      this.queueStatus,
      this.settingsDialog,
      this.settingsForm,
      this.toastContainer,
      this.monitorPanel,
      this.toggleSidebarButton,
      this.metricPrompt,
      this.metricCompletion,
      this.metricTotal,
      this.metricRateLimits,
      this.metricRetries,
      this.metricTtftP95,
      this.metricTtftList,
      this.metricFailures,
      this.modelSelect,
      this.manualModelInput,
      this.apiKeyInput,
      this.rememberKey,
      this.baseUrlInput,
      this.temperatureInput,
      this.topPInput,
      this.maxTokensInput,
      this.modelStatus,
      this.testConnectionButton,
      this.refreshModelsButton,
      this.clearKeyButton,
      this.exportButton,
      this.settingsButton,
      this.clearButton,
      this.exportMetricsButton,
      this.modalBackdrop,
    ];
    if (elements.some((el) => !(el instanceof HTMLElement))) {
      throw new Error('UI 元素初始化失败');
    }
  }

  attachEvents() {
    this.sendButton.addEventListener('click', () => {
      const value = this.textarea.value.trim();
      if (!value) {
        return;
      }
      this.dispatchEvent(new CustomEvent('send', { detail: { text: value } }));
    });

    this.textarea.addEventListener('keydown', (event) => {
      if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
        event.preventDefault();
        this.sendButton.click();
      }
    });

    this.settingsButton.addEventListener('click', () => {
      this.openSettings(this.store.snapshot());
    });

    this.clearButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('clear'));
    });

    this.exportButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('export-conversation'));
    });

    this.settingsForm.addEventListener('submit', (event) => {
      event.preventDefault();
      const formData = new FormData(this.settingsForm);
      const settings = this.store.getSettings();
      const updated = {
        baseUrl: String(formData.get('baseUrl') || settings.baseUrl || DEFAULT_BASE_URL),
        model: String(formData.get('manualModel') || formData.get('model') || settings.model),
        temperature: Number(formData.get('temperature') ?? settings.temperature),
        top_p: Number(formData.get('top_p') ?? settings.top_p),
        max_tokens: Number(formData.get('max_tokens') ?? settings.max_tokens),
        rememberKey: this.rememberKey.checked,
      };
      this.dispatchEvent(new CustomEvent('settings-save', { detail: { settings: updated, apiKey: this.apiKeyInput.value } }));
    });

    this.clearKeyButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('settings-clear-key'));
    });

    this.refreshModelsButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('settings-refresh-models'));
    });

    this.testConnectionButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('settings-test-connection'));
    });

    this.rememberKey.addEventListener('change', () => {
      if (this.rememberKey.checked) {
        this.showToast({
          title: '安全提醒',
          message: 'sessionStorage 在浏览器端保存凭证，仍有被同机用户读取的风险。',
          type: 'warning',
          duration: 7000,
        });
      }
    });

    this.modalBackdrop.addEventListener('click', () => {
      this.closeSettings();
    });

    const closeButton = document.getElementById('closeSettings');
    if (closeButton) {
      closeButton.addEventListener('click', () => this.closeSettings());
    }

    this.monitorPanel.addEventListener('click', (event) => {
      const target = event.target instanceof HTMLElement ? event.target : null;
      if (!target) {
        return;
      }
      if (target === this.toggleSidebarButton || target.closest('.sidebar-header')) {
        const collapsed = this.monitorPanel.getAttribute('data-collapsed') === 'true';
        this.toggleSidebar(collapsed);
      }
    });

    this.messageList.addEventListener('click', (event) => {
      const target = event.target instanceof HTMLElement ? event.target : null;
      if (!target) {
        return;
      }
      if (target.matches('button.cancel')) {
        const id = target.dataset.messageId;
        if (id) {
          this.dispatchEvent(new CustomEvent('cancel-request', { detail: { assistantMessageId: id } }));
        }
      }
      if (target.matches('button.retry')) {
        const id = target.dataset.messageId;
        if (id) {
          this.dispatchEvent(new CustomEvent('retry-request', { detail: { assistantMessageId: id } }));
        }
      }
      if (target.dataset.copyRequestId) {
        const value = target.dataset.copyRequestId;
        navigator.clipboard.writeText(value).then(() => {
          this.showToast({ message: 'request_id 已复制', type: 'success', duration: 2500 });
        }).catch((error) => {
          console.warn('复制 request_id 失败', error);
        });
      }
    });

    this.exportMetricsButton.addEventListener('click', () => {
      this.dispatchEvent(new CustomEvent('export-metrics'));
    });
  }

  /** @param {StoredMessage[]} messages */
  renderMessages(messages) {
    const container = this.messageList;
    const previousScroll = container.scrollHeight - container.scrollTop - container.clientHeight;
    const shouldScroll = previousScroll < 120;
    const existingIds = new Set(this.messageMap.keys());
    for (const message of messages) {
      let element = this.messageMap.get(message.id);
      if (!element) {
        element = this.createMessageElement(message);
        container.appendChild(element);
        this.messageMap.set(message.id, element);
      }
      existingIds.delete(message.id);
      this.updateMessageElement(element, message);
    }
    for (const id of existingIds) {
      const element = this.messageMap.get(id);
      if (element && element.parentElement === container) {
        container.removeChild(element);
      }
      this.messageMap.delete(id);
    }
    if (shouldScroll) {
      container.scrollTo({ top: container.scrollHeight, behavior: 'smooth' });
    }
  }

  updateQueueStatus(active, queued) {
    const text = queued > 0 ? `活动 ${active} · 排队 ${queued}` : active > 0 ? `活动 ${active}` : '队列空闲';
    this.queueStatus.textContent = text;
  }

  setSendEnabled(enabled) {
    this.sendButton.disabled = !enabled;
  }

  clearInput() {
    this.textarea.value = '';
  }

  focusInput() {
    this.textarea.focus();
  }

  /** @param {StoreSnapshot} snapshot */
  openSettings(snapshot) {
    const { settings, models } = snapshot;
    this.settingsDialog.removeAttribute('hidden');
    this.settingsDialog.setAttribute('aria-hidden', 'false');
    document.body.style.overflow = 'hidden';
    this.baseUrlInput.value = settings.baseUrl;
    this.temperatureInput.value = String(settings.temperature);
    this.topPInput.value = String(settings.top_p);
    this.maxTokensInput.value = String(settings.max_tokens);
    this.rememberKey.checked = settings.rememberKey;
    this.apiKeyInput.value = this.store.getApiKey();
    this.manualModelInput.value = settings.model;
    this.modelSelect.innerHTML = '';
    models.forEach((model) => {
      const option = document.createElement('option');
      option.value = model;
      option.textContent = model;
      if (model === settings.model) {
        option.selected = true;
      }
      this.modelSelect.appendChild(option);
    });
    this.modelStatus.textContent = snapshot.modelStatus;
    const firstField = this.settingsForm.querySelector('input,select,textarea,button');
    if (firstField instanceof HTMLElement) {
      firstField.focus();
    }
  }

  closeSettings() {
    this.settingsDialog.setAttribute('hidden', 'true');
    this.settingsDialog.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = '';
  }

  toggleSidebar(expanded) {
    this.monitorPanel.setAttribute('data-collapsed', expanded ? 'false' : 'true');
    this.toggleSidebarButton.setAttribute('aria-expanded', String(expanded));
  }

  /** @param {MetricsSnapshot} snapshot */
  updateMetrics(snapshot) {
    this.metricPrompt.textContent = snapshot.totals.prompt.toString();
    this.metricCompletion.textContent = snapshot.totals.completion.toString();
    this.metricTotal.textContent = snapshot.totals.total.toString();
    this.metricRateLimits.textContent = snapshot.rateLimitCount.toString();
    this.metricRetries.textContent = snapshot.retryCount.toString();
    this.metricTtftP95.textContent = snapshot.ttftP95 != null ? `${snapshot.ttftP95} ms` : '-';
    this.metricTtftList.innerHTML = '';
    snapshot.ttft.forEach((ms) => {
      const li = document.createElement('li');
      li.textContent = `${ms.toFixed(0)} ms`;
      this.metricTtftList.appendChild(li);
    });
    this.metricFailures.innerHTML = '';
    const entries = Object.entries(snapshot.failures);
    if (entries.length === 0) {
      const li = document.createElement('li');
      li.textContent = '暂无失败记录';
      this.metricFailures.appendChild(li);
    } else {
      entries.forEach(([code, count]) => {
        const li = document.createElement('li');
        li.textContent = `${code}: ${count}`;
        this.metricFailures.appendChild(li);
      });
    }
  }

  /** @param {string} text */
  setModelStatus(text) {
    this.modelStatus.textContent = text;
  }

  /** @param {{ title?: string; message: string; type?: 'info'|'error'|'success'|'warning'; duration?: number; actions?: Array<{ label: string; action: () => void }> }} options */
  showToast(options) {
    const toast = document.createElement('div');
    toast.className = 'toast';
    if (options.type === 'error') {
      toast.classList.add('error');
    }
    if (options.type === 'success') {
      toast.classList.add('success');
    }
    if (options.title) {
      const title = document.createElement('div');
      title.className = 'title';
      title.textContent = options.title;
      toast.appendChild(title);
    }
    const message = document.createElement('div');
    message.textContent = options.message;
    toast.appendChild(message);
    if (options.actions && options.actions.length > 0) {
      const actions = document.createElement('div');
      actions.className = 'toast-actions';
      options.actions.forEach((action) => {
        const button = document.createElement('button');
        button.type = 'button';
        button.textContent = action.label;
        button.addEventListener('click', () => {
          action.action();
          dismiss();
        });
        actions.appendChild(button);
      });
      toast.appendChild(actions);
    }
    this.toastContainer.appendChild(toast);
    let timeoutId;
    const dismiss = () => {
      if (timeoutId) {
        window.clearTimeout(timeoutId);
      }
      if (toast.parentElement) {
        toast.parentElement.removeChild(toast);
      }
    };
    const duration = options.duration ?? (options.actions && options.actions.length > 0 ? undefined : 5000);
    if (typeof duration === 'number' && duration > 0) {
      timeoutId = window.setTimeout(dismiss, duration);
    }
    return { dismiss };
  }

  /** @param {StoredMessage} message */
  createMessageElement(message) {
    const wrapper = document.createElement('div');
    wrapper.className = `message ${message.role}`;
    wrapper.dataset.messageId = message.id;
    const bubble = document.createElement('div');
    bubble.className = 'bubble';
    const content = document.createElement('div');
    content.className = 'content';
    bubble.appendChild(content);
    const meta = document.createElement('div');
    meta.className = 'meta';
    bubble.appendChild(meta);
    wrapper.appendChild(bubble);
    return wrapper;
  }

  /** @param {HTMLElement} element @param {StoredMessage} message */
  updateMessageElement(element, message) {
    element.className = `message ${message.role}`;
    const bubble = element.querySelector('.bubble');
    const content = bubble ? bubble.querySelector('.content') : null;
    const meta = bubble ? bubble.querySelector('.meta') : null;
    if (!(bubble instanceof HTMLElement) || !(content instanceof HTMLElement) || !(meta instanceof HTMLElement)) {
      return;
    }
    content.textContent = message.content;
    meta.innerHTML = '';
    if (message.autoGenerated) {
      const badge = document.createElement('span');
      badge.className = 'label';
      badge.textContent = '自动续写';
      meta.appendChild(badge);
    }
    if (message.statusNote) {
      const note = document.createElement('span');
      note.textContent = message.statusNote;
      meta.appendChild(note);
    }
    if (message.finishReason) {
      const span = document.createElement('span');
      span.textContent = `finish_reason: ${message.finishReason}`;
      meta.appendChild(span);
    }
    if (message.usage) {
      const span = document.createElement('span');
      const prompt = message.usage.prompt_tokens ?? 0;
      const completion = message.usage.completion_tokens ?? 0;
      const total = message.usage.total_tokens ?? prompt + completion;
      span.textContent = `tokens p:${prompt} c:${completion} t:${total}`;
      meta.appendChild(span);
    }
    if (message.requestId) {
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'ghost';
      button.dataset.copyRequestId = message.requestId;
      button.textContent = '复制 request_id';
      meta.appendChild(button);
    }
    if (message.error) {
      const error = document.createElement('span');
      error.className = 'error';
      error.textContent = message.error;
      meta.appendChild(error);
      const retry = document.createElement('button');
      retry.type = 'button';
      retry.className = 'retry';
      retry.dataset.messageId = message.id;
      retry.textContent = '立即重试';
      meta.appendChild(retry);
    }
    if (message.streaming) {
      const cancel = document.createElement('button');
      cancel.type = 'button';
      cancel.className = 'cancel';
      cancel.dataset.messageId = message.id;
      cancel.textContent = '取消';
      meta.appendChild(cancel);
    }
  }
}

class ChatApp {
  /** @param {Store} store @param {Metrics} metrics @param {ApiClient} api @param {UI} ui */
  constructor(store, metrics, api, ui) {
    this.store = store;
    this.metrics = metrics;
    this.api = api;
    this.ui = ui;
    this.queue = [];
    this.active = new Map();
    this.bindUI();
  }

  async init() {
    this.store.subscribe((snapshot) => {
      this.ui.renderMessages(snapshot.messages);
      this.ui.setModelStatus(snapshot.modelStatus);
    });
    this.metrics.subscribe((snapshot) => {
      this.ui.updateMetrics(snapshot);
    });
    if (this.store.getMessages().length === 0) {
      this.store.addMessage({
        id: createId(),
        role: 'assistant',
        content: '欢迎使用 Gradient Serverless Chat！请先点击右上角“设置 ⚙️”填写 API Key，然后刷新模型列表并选择合适的模型。',
        createdAt: Date.now(),
        autoGenerated: true,
        statusNote: '提示',
      });
    }
    this.ui.updateQueueStatus(0, 0);
    this.ui.focusInput();
    try {
      await this.fetchModelsWithRetry(false);
    } catch (error) {
      console.warn('初始化模型列表失败', error);
      this.store.setModelStatus('离线模式：未能加载模型列表，请手动输入。');
    }
  }

  bindUI() {
    this.ui.addEventListener('send', (event) => {
      const detail = event.detail || { text: '' };
      this.handleSend(detail.text, {});
    });
    this.ui.addEventListener('clear', () => {
      this.clearConversation();
    });
    this.ui.addEventListener('export-conversation', () => {
      this.exportConversation();
    });
    this.ui.addEventListener('settings-save', (event) => {
      const detail = event.detail || { settings: this.store.getSettings(), apiKey: '' };
      this.saveSettings(detail.settings, detail.apiKey);
    });
    this.ui.addEventListener('settings-clear-key', () => {
      this.store.clearApiKey();
      this.ui.showToast({ message: '已清除 API Key', type: 'info', duration: 2500 });
      this.ui.openSettings(this.store.snapshot());
    });
    this.ui.addEventListener('settings-refresh-models', () => {
      this.fetchModelsWithRetry(true).catch((error) => {
        console.warn('刷新模型失败', error);
      });
    });
    this.ui.addEventListener('settings-test-connection', () => {
      this.testConnection();
    });
    this.ui.addEventListener('cancel-request', (event) => {
      const detail = event.detail || { assistantMessageId: '' };
      this.cancelRequest(detail.assistantMessageId);
    });
    this.ui.addEventListener('retry-request', (event) => {
      const detail = event.detail || { assistantMessageId: '' };
      this.retryAssistant(detail.assistantMessageId);
    });
    this.ui.addEventListener('export-metrics', () => {
      this.exportMetrics();
    });
  }

  /** @param {string} text @param {SendOptions} options */
  handleSend(text, options) {
    const trimmed = text.trim();
    if (!trimmed) {
      return;
    }
    const settings = this.store.getSettings();
    const userMessage = this.store.addMessage({
      id: createId(),
      role: 'user',
      content: trimmed,
      streaming: false,
      queued: false,
      autoGenerated: options.autoGenerated ?? false,
      statusNote: options.autoGenerated ? '自动续写' : undefined,
    });
    this.enqueueAssistant(userMessage.id, options.autoGenerated ?? false, options.autoDepth ?? 0, options.maxTokens ?? settings.max_tokens);
    if (!options.autoGenerated) {
      this.ui.clearInput();
    }
    this.ui.focusInput();
  }

  /** @param {string} assistantMessageId */
  cancelRequest(assistantMessageId) {
    const active = this.active.get(assistantMessageId);
    if (active) {
      active.controller.abort();
      this.ui.showToast({ message: '已发送取消请求', type: 'info', duration: 2000 });
    }
  }

  /** @param {string} assistantMessageId */
  retryAssistant(assistantMessageId) {
    const messages = this.store.getMessages();
    const index = messages.findIndex((msg) => msg.id === assistantMessageId);
    if (index <= 0) {
      this.ui.showToast({ message: '未找到可重试的消息', type: 'error', duration: 3000 });
      return;
    }
    const userMessage = messages[index - 1];
    if (!userMessage || userMessage.role !== 'user') {
      this.ui.showToast({ message: '无法定位对应的用户消息', type: 'error', duration: 3000 });
      return;
    }
    this.store.updateMessage(assistantMessageId, {
      content: '',
      streaming: true,
      queued: true,
      error: null,
      statusNote: '重新排队…',
      usage: undefined,
      finishReason: undefined,
    });
    const settings = this.store.getSettings();
    const queueItem = {
      id: createId(),
      userMessageId: userMessage.id,
      assistantMessageId,
      autoGenerated: userMessage.autoGenerated ?? false,
      autoDepth: 0,
      maxTokens: settings.max_tokens,
      controller: new AbortController(),
    };
    this.queue.unshift(queueItem);
    this.processQueue();
    this.metrics.recordRetry();
  }

  clearConversation() {
    for (const item of this.active.values()) {
      item.controller.abort();
    }
    this.queue = [];
    this.active.clear();
    this.store.clearMessages();
    this.store.addMessage({
      id: createId(),
      role: 'assistant',
      content: '对话已清除。请再次输入或打开设置更新参数。',
      createdAt: Date.now(),
      autoGenerated: true,
      statusNote: '提示',
    });
    this.ui.updateQueueStatus(0, 0);
  }

  /** @param {AppSettings} settings @param {string} apiKey */
  saveSettings(settings, apiKey) {
    const sanitizedBase = settings.baseUrl.trim() || DEFAULT_BASE_URL;
    this.store.updateSettings({
      baseUrl: sanitizedBase,
      model: settings.model,
      temperature: clampNumber(settings.temperature, 0, 2),
      top_p: clampNumber(settings.top_p, 0, 1),
      max_tokens: Math.max(1, Math.floor(settings.max_tokens)),
      rememberKey: settings.rememberKey,
    });
    this.store.setApiKey(apiKey.trim());
    this.ui.showToast({ message: '设置已保存', type: 'success', duration: 2500 });
    this.ui.closeSettings();
  }

  async exportConversation() {
    const data = {
      exportedAt: new Date().toISOString(),
      baseUrl: this.store.getSettings().baseUrl,
      model: this.store.getSettings().model,
      messages: this.store.getMessages().map((msg) => ({
        id: msg.id,
        role: msg.role,
        content: msg.content,
        createdAt: msg.createdAt,
        finishReason: msg.finishReason,
        usage: msg.usage,
        requestId: msg.requestId,
        autoGenerated: msg.autoGenerated ?? false,
        statusNote: msg.statusNote,
        error: msg.error,
      })),
    };
    downloadText(`gradient-chat-${Date.now()}.json`, JSON.stringify(data, null, 2), 'application/json');
    this.ui.showToast({ message: '对话已导出', type: 'success', duration: 2500 });
  }

  exportMetrics() {
    const text = this.metrics.exportNDJSON();
    downloadText(`gradient-metrics-${Date.now()}.ndjson`, text, 'application/x-ndjson');
    this.ui.showToast({ message: '监控指标已导出', type: 'success', duration: 2500 });
  }

  async testConnection() {
    try {
      await this.api.testConnection();
      this.ui.showToast({ message: '连接正常，密钥有效。', type: 'success', duration: 2500 });
    } catch (error) {
      if (error instanceof ApiError) {
        this.ui.showToast({ message: `连接失败：${error.message}`, type: 'error', duration: 4000 });
      } else {
        this.ui.showToast({ message: '连接失败，请检查网络', type: 'error', duration: 4000 });
      }
    }
  }

  async fetchModelsWithRetry(showToast) {
    const backoff = new Backoff(1000, 2, 8000, 4);
    let attempt = 0;
    while (attempt <= backoff.maxAttempts) {
      try {
        const models = await this.api.fetchModels();
        this.store.setModels(models);
        this.store.setModelStatus(`已加载 ${models.length} 个模型`);
        if (showToast) {
          this.ui.showToast({ message: '模型列表已更新', type: 'success', duration: 2500 });
        }
        return;
      } catch (error) {
        attempt += 1;
        if (error instanceof ApiError && error.status === 401) {
          this.store.setModelStatus('401 未授权，请检查 API Key。');
          this.ui.showToast({ message: '模型列表需要有效的 API Key。', type: 'error', duration: 4000 });
          return;
        }
        if (attempt > backoff.maxAttempts) {
          this.store.setModelStatus('离线模式：无法拉取模型，请手动输入。');
          if (showToast) {
            this.ui.showToast({ message: '进入离线模式，请手动填写模型 ID。', type: 'warning', duration: 5000 });
          }
          return;
        }
        const delay = backoff.next();
        this.store.setModelStatus(`拉取失败（第 ${attempt} 次），${Math.round(delay / 1000)} 秒后重试…`);
        await sleep(delay);
      }
    }
  }

  /** @param {string} userMessageId @param {boolean} autoGenerated @param {number} autoDepth @param {number} maxTokens */
  enqueueAssistant(userMessageId, autoGenerated, autoDepth, maxTokens) {
    const assistantMessage = this.store.addMessage({
      id: createId(),
      role: 'assistant',
      content: '',
      streaming: true,
      queued: true,
      statusNote: '排队中…',
      autoGenerated,
    });
    const queueItem = {
      id: createId(),
      userMessageId,
      assistantMessageId: assistantMessage.id,
      autoGenerated,
      autoDepth,
      maxTokens,
      controller: new AbortController(),
    };
    this.queue.push(queueItem);
    this.processQueue();
  }

  processQueue() {
    while (this.active.size < MAX_CONCURRENT_STREAMS && this.queue.length > 0) {
      const item = this.queue.shift();
      if (!item) {
        break;
      }
      this.startQueueItem(item);
    }
    this.ui.updateQueueStatus(this.active.size, this.queue.length);
  }

  /** @param {ChatQueueItem} item */
  startQueueItem(item) {
    this.active.set(item.assistantMessageId, item);
    this.store.updateMessage(item.assistantMessageId, {
      queued: false,
      streaming: true,
      statusNote: '生成中…',
      error: null,
      requestId: null,
    });
    this.ui.updateQueueStatus(this.active.size, this.queue.length);
    this.runQueueItem(item)
      .catch((error) => {
        console.warn('请求失败', error);
      })
      .finally(() => {
        this.active.delete(item.assistantMessageId);
        this.processQueue();
      });
  }

  /** @param {ChatQueueItem} item */
  async runQueueItem(item) {
    const assistantId = item.assistantMessageId;
    const rateLimitMax = 5;
    let rateLimitAttempts = 0;
    const backoff = new Backoff(1000, 2, 8000, 4);
    let aggregated = '';
    const buildPayload = () => ({
      model: this.store.getSettings().model,
      messages: this.buildConversationForAssistant(assistantId),
      temperature: this.store.getSettings().temperature,
      top_p: this.store.getSettings().top_p,
      max_tokens: Math.max(1, Math.floor(item.maxTokens)),
    });

    while (true) {
      try {
        const result = await this.api.streamChat(buildPayload(), {
          signal: item.controller.signal,
          onDelta: (delta) => {
            aggregated += delta;
            this.store.updateMessage(assistantId, { content: aggregated });
          },
          onRequestId: (requestId) => {
            this.store.updateMessage(assistantId, { requestId });
          },
        });
        aggregated = result.content;
        this.store.updateMessage(assistantId, {
          content: aggregated,
          streaming: false,
          finishReason: result.finishReason ?? 'stop',
          usage: result.usage,
          statusNote: result.notice ?? '',
        });
        this.metrics.recordRequestSummary({ status: 200, ttft: result.ttft, finishReason: result.finishReason, note: result.notice });
        if (result.finishReason === 'length' && item.autoDepth < AUTO_CONTINUE_LIMIT) {
          const nextTokens = Math.max(MIN_AUTO_MAX_TOKENS, Math.floor(item.maxTokens * AUTO_CONTINUE_REDUCTION));
          this.ui.showToast({ message: `因长度限制自动续写（第 ${item.autoDepth + 1} 次）`, type: 'info', duration: 3000 });
          this.handleSend('continue', { autoGenerated: true, autoDepth: item.autoDepth + 1, maxTokens: nextTokens });
        }
        return;
      } catch (error) {
        const errorName = error && typeof error === 'object' && 'name' in error ? String(error.name) : '';
        if (item.controller.signal.aborted || errorName === 'AbortError') {
          this.store.updateMessage(assistantId, { streaming: false, statusNote: '已取消', error: '请求已取消' });
          this.metrics.recordFailure('abort');
          return;
        }
        if (error instanceof ApiError) {
          if (error.status === 401) {
            this.store.updateMessage(assistantId, { streaming: false, error: '密钥无效或已过期', statusNote: '' });
            this.metrics.recordFailure('401');
            this.ui.showToast({ message: '401 未授权，请检查 API Key。', type: 'error', duration: 4000 });
            return;
          }
          if (error.status === 400) {
            this.store.updateMessage(assistantId, { streaming: false, error: error.message, statusNote: '' });
            this.metrics.recordFailure('400');
            this.metrics.recordRequestSummary({ status: 400, note: error.message });
            return;
          }
          if (error.status === 429) {
            rateLimitAttempts += 1;
            this.metrics.recordRateLimit();
            this.metrics.recordRetry();
            if (rateLimitAttempts > rateLimitMax) {
              this.store.updateMessage(assistantId, { streaming: false, error: '多次触发限流，请稍后重试', statusNote: '' });
              this.metrics.recordFailure('429');
              return;
            }
            const retryAfter = error.headers ? error.headers.get('retry-after') : null;
            let delay = 1000;
            if (retryAfter) {
              const parsed = Number(retryAfter);
              if (!Number.isNaN(parsed)) {
                delay = Math.max(1000, Math.round(parsed * 1000));
              }
            }
            this.store.updateMessage(assistantId, { statusNote: `速率限制，${Math.round(delay / 1000)}s 后重试…` });
            const action = await this.waitForRetry(item, delay, '速率限制，等待后重试');
            if (action === 'cancel') {
              this.store.updateMessage(assistantId, { streaming: false, error: '已取消重试', statusNote: '' });
              this.metrics.recordFailure('429-cancel');
              return;
            }
            if (action === 'retry' || action === 'continue') {
              continue;
            }
          }
          if (error.status >= 500 && error.status < 600) {
            if (backoff.attempt >= backoff.maxAttempts) {
              this.store.updateMessage(assistantId, { streaming: false, error: `服务异常：${error.status}`, statusNote: '' });
              this.metrics.recordFailure(String(error.status));
              return;
            }
            const delay = backoff.next();
            this.metrics.recordRetry();
            this.store.updateMessage(assistantId, { statusNote: `服务异常，${Math.round(delay / 1000)}s 后重试…` });
            const action = await this.waitForRetry(item, delay, '服务异常，等待重试');
            if (action === 'cancel') {
              this.store.updateMessage(assistantId, { streaming: false, error: '已取消重试', statusNote: '' });
              this.metrics.recordFailure('5xx-cancel');
              return;
            }
            if (action === 'retry' || action === 'continue') {
              continue;
            }
          }
          this.store.updateMessage(assistantId, { streaming: false, error: error.message, statusNote: '' });
          this.metrics.recordFailure(String(error.status));
          this.metrics.recordRequestSummary({ status: error.status, note: error.message });
          return;
        }
        this.metrics.recordRetry();
        this.store.updateMessage(assistantId, { statusNote: '网络异常，1s 后重试…' });
        const action = await this.waitForRetry(item, 1000, '网络异常，等待重试');
        if (action === 'cancel') {
          this.store.updateMessage(assistantId, { streaming: false, error: '已取消重试', statusNote: '' });
          this.metrics.recordFailure('network-cancel');
          return;
        }
      }
    }
  }

  /** @param {ChatQueueItem} item @param {number} delayMs @param {string} message */
  async waitForRetry(item, delayMs, message) {
    return new Promise((resolve) => {
      let settled = false;
      const handle = this.ui.showToast({
        title: '等待重试',
        message: `${message}（${Math.round(delayMs / 1000)}s）`,
        type: 'warning',
        actions: [
          {
            label: '立即重试',
            action: () => {
              if (!settled) {
                settled = true;
                resolve('retry');
              }
            },
          },
          {
            label: '取消',
            action: () => {
              if (!settled) {
                settled = true;
                item.controller.abort();
                resolve('cancel');
              }
            },
          },
        ],
      });
      const timer = window.setTimeout(() => {
        if (!settled) {
          settled = true;
          handle.dismiss();
          resolve('continue');
        }
      }, delayMs);
      const onAbort = () => {
        if (!settled) {
          settled = true;
          window.clearTimeout(timer);
          handle.dismiss();
          resolve('cancel');
        }
      };
      item.controller.signal.addEventListener('abort', onAbort, { once: true });
    });
  }

  /** @param {string} assistantId @returns {OutgoingMessage[]} */
  buildConversationForAssistant(assistantId) {
    const messages = this.store.getMessages();
    const filtered = [];
    for (const message of messages) {
      if (message.id === assistantId) {
        break;
      }
      filtered.push({ role: message.role, content: message.content });
    }
    return filtered;
  }
}

function createId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function clampNumber(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function sleep(ms) {
  if (ms <= 0) {
    return Promise.resolve();
  }
  return new Promise((resolve) => {
    window.setTimeout(resolve, ms);
  });
}

function downloadText(filename, text, mime) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function bootstrap() {
  const store = new Store();
  const metrics = new Metrics();
  const api = new ApiClient(store, metrics);
  const ui = new UI(store, metrics);
  const app = new ChatApp(store, metrics, api, ui);
  app.init().catch((error) => console.error('初始化失败', error));
  runSelfTests();
}

function runSelfTests() {
  const results = [];
  const logResults = () => {
    if (results.length >= 3) {
      console.group('自检结果');
      results.forEach((result) => {
        if (result.passed) {
          console.log(`✅ ${result.name}`);
        } else {
          console.warn(`❌ ${result.name}`, result.error);
        }
      });
      console.groupEnd();
    }
  };
  const test = (name, fn) => {
    try {
      const value = fn();
      if (value instanceof Promise) {
        value
          .then(() => {
            results.push({ name, passed: true });
            logResults();
          })
          .catch((error) => {
            results.push({ name, passed: false, error });
            logResults();
          });
      } else {
        results.push({ name, passed: true });
        logResults();
      }
    } catch (error) {
      results.push({ name, passed: false, error });
      logResults();
    }
  };

  test('Backoff 递增', () => {
    const backoff = new Backoff(1000, 2, 8000, 4);
    const values = [backoff.next(), backoff.next(), backoff.next(), backoff.next()];
    if (values.join(',') !== '1000,2000,4000,8000') {
      throw new Error('回退序列不符合预期');
    }
  });

  test('Metrics p95', () => {
    const metrics = new Metrics();
    [10, 20, 30, 40, 50].forEach((ms) => metrics.recordTTFT(ms));
    const snapshot = metrics.snapshot();
    if (snapshot.ttftP95 !== 50) {
      throw new Error(`p95 预期为 50，实际 ${snapshot.ttftP95}`);
    }
  });

  test('SSE 解析', async () => {
    const chunks = ['data: {"choices":[{"delta":{"content":"Hello"}}]}\n\n', 'data: [DONE]\n\n'];
    const stream = new ReadableStream({
      start(controller) {
        chunks.forEach((chunk) => controller.enqueue(new TextEncoder().encode(chunk)));
        controller.close();
      },
    });
    const parts = [];
    for await (const line of SseParser.streamLines(stream)) {
      parts.push(line);
    }
    if (parts.length !== 2 || !parts[0].includes('Hello') || parts[1] !== '[DONE]') {
      throw new Error('SSE 解析失败');
    }
  });
}

bootstrap();
